import 'dart:convert';
import 'dart:io';
import '../../core/models/models.dart';

class DPOFlywheelReport {
  final int totalFeedbackProcessed;
  final int validPairsGenerated;
  final int rejectedCount;
  final double averageTokenDelta;
  final String outputPath;
  final String trainingScriptPath;

  DPOFlywheelReport({
    required this.totalFeedbackProcessed,
    required this.validPairsGenerated,
    required this.rejectedCount,
    required this.averageTokenDelta,
    required this.outputPath,
    required this.trainingScriptPath,
  });

  Map<String, dynamic> toJson() => {
        'total_feedback_processed': totalFeedbackProcessed,
        'valid_pairs_generated': validPairsGenerated,
        'rejected_count': rejectedCount,
        'average_token_delta': averageTokenDelta,
        'output_path': outputPath,
        'training_script_path': trainingScriptPath,
      };

  String toMarkdown() {
    final buf = StringBuffer();
    buf.writeln('# 🔄 Automated DPO Flywheel Report');
    buf.writeln();
    buf.writeln('| Metric | Count / Value |');
    buf.writeln('|---|---|');
    buf.writeln('| **Total Feedback Signals Processed** | $totalFeedbackProcessed |');
    buf.writeln('| **DPO Preference Pairs Formatted** | $validPairsGenerated |');
    buf.writeln('| **Low-Quality / Deduplicated Drops** | $rejectedCount |');
    buf.writeln('| **Average Token Delta (|Chosen - Rejected|)** | ${averageTokenDelta.toStringAsFixed(1)} tokens |');
    buf.writeln('| **DPO Dataset Path** | `$outputPath` |');
    buf.writeln('| **LoRA Nightly Fine-Tune Script** | `$trainingScriptPath` |');
    buf.writeln();
    buf.writeln('### Dataset Sample');
    buf.writeln('```json');
    buf.writeln(jsonEncode({
      'prompt': 'User query sample...',
      'chosen': 'Verified optimal model response...',
      'rejected': 'Hallucinated or unsafe response...'
    }));
    buf.writeln('```');
    return buf.toString();
  }
}

class DPOFlywheel {
  final String outputDir;

  DPOFlywheel({this.outputDir = 'data/dpo_feedback'});

  /// Processes raw production feedback into curated DPO pairs and generates LoRA fine-tuning script
  DPOFlywheelReport processFeedback({
    required List<DPOPair> rawPairs,
    String datasetFileName = 'dpo_dataset.jsonl',
  }) {
    final outDirectory = Directory(outputDir);
    outDirectory.createSync(recursive: true);

    final validPairs = <DPOPair>[];
    final seenPrompts = <String>{};
    int dropped = 0;
    double tokenDeltaSum = 0.0;

    for (final pair in rawPairs) {
      final promptClean = pair.prompt.trim();
      final chosenClean = pair.chosen.trim();
      final rejectedClean = pair.rejected.trim();

      // Quality Filters
      if (promptClean.length < 5 || chosenClean.isEmpty || rejectedClean.isEmpty) {
        dropped++;
        continue;
      }
      if (chosenClean == rejectedClean) {
        dropped++; // Identical answers give no preference signal
        continue;
      }
      if (seenPrompts.contains(promptClean)) {
        dropped++; // Deduplication
        continue;
      }

      seenPrompts.add(promptClean);
      final delta = (chosenClean.split(' ').length - rejectedClean.split(' ').length).abs();
      tokenDeltaSum += delta;

      validPairs.add(DPOPair(
        id: pair.id,
        prompt: promptClean,
        chosen: chosenClean,
        rejected: rejectedClean,
        source: pair.source,
        metadata: {
          ...pair.metadata,
          'processed_at': DateTime.now().toIso8601String(),
        },
      ));
    }

    final datasetPath = '$outputDir/$datasetFileName';
    final datasetFile = File(datasetPath);
    final sink = datasetFile.openWrite();
    for (final p in validPairs) {
      sink.writeln(jsonEncode({
        'prompt': p.prompt,
        'chosen': p.chosen,
        'rejected': p.rejected,
      }));
    }
    sink.close();

    // Generate nightly LoRA fine-tune script (compatible with Unsloth / Hugging Face TRL)
    final scriptPath = '$outputDir/train_nightly_lora.sh';
    final scriptContent = '''#!/usr/bin/env bash
# Automated Nightly DPO LoRA Fine-Tuning Script
# Generated by Evaluator DPO Flywheel

set -euo pipefail

DATASET_PATH="$datasetPath"
MODEL_NAME="THUDM/glm-4-9b-chat" # Base model for GLM family
OUTPUT_DIR="models/lora_checkpoints/\$(date +%Y%m%d_%H%M%S)"
BETA=0.1
LEARNING_RATE=5e-6
LORA_R=16
LORA_ALPHA=32

echo "🚀 Starting Nightly DPO Fine-Tune on \$DATASET_PATH..."
echo "Output will be saved to \$OUTPUT_DIR"

# Sample command using standard trl / dpo_trainer:
# python -m trl.commands.dpo \\
#   --model_name_or_path "\$MODEL_NAME" \\
#   --dataset_name "\$DATASET_PATH" \\
#   --output_dir "\$OUTPUT_DIR" \\
#   --learning_rate \$LEARNING_RATE \\
#   --per_device_train_batch_size 2 \\
#   --gradient_accumulation_steps 8 \\
#   --dpo_beta \$BETA \\
#   --lora_r \$LORA_R \\
#   --lora_alpha \$LORA_ALPHA

echo "✅ DPO dataset prepared and fine-tuning trigger dispatched."
''';

    final scriptFile = File(scriptPath);
    scriptFile.writeAsStringSync(scriptContent);
    // Make script executable
    try {
      Process.runSync('chmod', ['+x', scriptPath]);
    } catch (_) {}

    final avgDelta = validPairs.isNotEmpty ? tokenDeltaSum / validPairs.length : 0.0;

    return DPOFlywheelReport(
      totalFeedbackProcessed: rawPairs.length,
      validPairsGenerated: validPairs.length,
      rejectedCount: dropped,
      averageTokenDelta: avgDelta,
      outputPath: datasetPath,
      trainingScriptPath: scriptPath,
    );
  }
}
